// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNiwjB3rljoSjGeuF_OVk7vnesbL0-XU',
    appId: '1:532619126727:web:973b5beb47fad7d5589be2',
    messagingSenderId: '532619126727',
    projectId: 'chat-ni-boss',
    authDomain: 'chat-ni-boss.firebaseapp.com',
    storageBucket: 'chat-ni-boss.appspot.com',
    measurementId: 'G-HLQKTSNRHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWd3rgSkMNw4Ukw__Xcns5sV4eyrxl_sI',
    appId: '1:532619126727:android:88ab8e2be8445959589be2',
    messagingSenderId: '532619126727',
    projectId: 'chat-ni-boss',
    storageBucket: 'chat-ni-boss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbReJd1OPiW4GI7sBnnMY1_yku8Na7MVw',
    appId: '1:532619126727:ios:a965bcf74f0152b6589be2',
    messagingSenderId: '532619126727',
    projectId: 'chat-ni-boss',
    storageBucket: 'chat-ni-boss.appspot.com',
    iosClientId: '532619126727-40in26vt9m2mk4jgs5vu4sff69c8j410.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbReJd1OPiW4GI7sBnnMY1_yku8Na7MVw',
    appId: '1:532619126727:ios:a965bcf74f0152b6589be2',
    messagingSenderId: '532619126727',
    projectId: 'chat-ni-boss',
    storageBucket: 'chat-ni-boss.appspot.com',
    iosClientId: '532619126727-40in26vt9m2mk4jgs5vu4sff69c8j410.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
